package com.mychat_sys.Vo;

public class UserVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_users.id
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_users.username
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_users.face_image
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    private String faceImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_users.face_image_big
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    private String faceImageBig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_users.nickname
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_users.qrcode
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    private String qrcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_users.id
     *
     * @return the value of chat_users.id
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_users.id
     *
     * @param id the value for chat_users.id
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_users.username
     *
     * @return the value of chat_users.username
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_users.username
     *
     * @param username the value for chat_users.username
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_users.face_image
     *
     * @return the value of chat_users.face_image
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public String getFaceImage() {
        return faceImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_users.face_image
     *
     * @param faceImage the value for chat_users.face_image
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public void setFaceImage(String faceImage) {
        this.faceImage = faceImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_users.face_image_big
     *
     * @return the value of chat_users.face_image_big
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public String getFaceImageBig() {
        return faceImageBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_users.face_image_big
     *
     * @param faceImageBig the value for chat_users.face_image_big
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public void setFaceImageBig(String faceImageBig) {
        this.faceImageBig = faceImageBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_users.nickname
     *
     * @return the value of chat_users.nickname
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_users.nickname
     *
     * @param nickname the value for chat_users.nickname
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_users.qrcode
     *
     * @return the value of chat_users.qrcode
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_users.qrcode
     *
     * @param qrcode the value for chat_users.qrcode
     *
     * @mbggenerated Thu Aug 26 15:58:05 CST 2021
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }


}
